language: python
script: make test_long
matrix:
  exclude:
    - python: "3.3"
      env: MATPLOTLIB_VERSION=2.0.*
  include:
    - python: "2.7"
      env: MATPLOTLIB_VERSION=1.1.1
    - python: "2.7"
      env: MATPLOTLIB_VERSION=1.2.0

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - MATPLOTLIB_VERSION=1.4.3
  - MATPLOTLIB_VERSION=1.5.*
  - MATPLOTLIB_VERSION=2.0.*
install:
  - pip install mock
  - pip install matplotlib==${MATPLOTLIB_VERSION}
